name: Python package

on: [push]
env:
  auth: ${{secrets.AUTH}}
  authToken: ${{secrets.AUTHTOKEN}}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install chromedriver-py
          pip install chromedriver-autoinstaller selenium pyvirtualdisplay
          pip install axe-devtools-api axe-devtools-unittest axe-devtools-selenium --extra-index-url https://${{secrets.EMAIL}}:${{secrets.APIKEY}}@agora.dequecloud.com/artifactory/api/pypi/devtools-python/simple
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: install cli
        run: |
        npm install @axe-devtools/cli  
      - name: Test with unnittest
        run: |
          python ./unitTestA11y.py